language: android
android:
  components:
    # - tools
    # - platform-tools

    # The BuildTools version
    - build-tools-26.0.2

    # The SDK version
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
